#!/bin/bash
if [ -f "/etc/hosts.bak" ]
then
	cp -a /etc/hosts.bak /etc/hosts
	cat /etc/BLACKLIST >> /etc/hosts
	rm /etc/BLACKLIST
	killall -9 mDNSResponder
	exit 0
else
      mv /etc/hosts /etc/hosts.bak
	cp -a /etc/hosts.bak /etc/hosts
	cat /etc/BLACKLIST >> /etc/hosts
	rm /etc/BLACKLIST
	killall -9 mDNSResponder
	exit 0
fi